import {
  AnalysisRecord,
  HealthResponse,
  ModelInfo,
  AudioFormatsResponse,
} from '../types/api';

export const INITIAL_MOCK_MODEL: ModelInfo = {
  name: 'PandaMIND Detector',
  version: 'phase9-experimental',
  status: 'active',
  calibration_status: 'calibrated',
  temperature: 0.65,
  operating_points: {
    fpr_0_1: 0.7556,
    fpr_1: 0.7556,
    fpr_5: 0.7556,
  },
  thresholds: {
    low: 0.7408,
    high: 0.7556,
  },
  supported_languages: ['en', 'hi', 'ta', 'hinglish'],
};

export const INITIAL_MOCK_FORMATS: AudioFormatsResponse = {
  supported_extensions: ['.wav', '.mp3', '.flac', '.ogg', '.m4a'],
  max_file_size_bytes: 26214400, // 25 MB
  max_duration_seconds: 300, // 5 minutes
};

export const INITIAL_MOCK_HEALTH: HealthResponse = {
  status: 'ok',
  version: '1.0.0',
  model_loaded: true,
  model_version: 'phase9-experimental',
  timestamp: new Date().toISOString(),
};

// 6 Core Pre-populated Test Cases for immediate inspection
export const MOCK_ANALYSES_SEED: AnalysisRecord[] = [
  {
    analysis_id: 'ana_human_001',
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 2 + 3000).toISOString(),
    status: 'completed',
    verdict: 'consistent_with_human',
    synthetic_probability: 0.12,
    confidence: 0.91,
    error_code: null,
    error_message: null,
    audio: {
      filename: 'indic_doctor_consultation_hi.wav',
      file_size_bytes: 4821040,
      duration_seconds: 18.4,
      sample_rate: 16000,
      channels: 1,
      format: 'WAV',
      language: 'hi',
      degradation: 'clean',
      source: 'indic_medical_corpus',
    },
    model: {
      name: 'PandaMIND Detector',
      version: 'phase9-experimental',
    },
    evidence: {
      signal_contributions: [
        {
          feature: 'Frame Energy Modulation',
          weight: 0.42,
          description: 'Natural temporal pitch & energy variations consistent with human vocal apparatus',
          direction: 'human_bias',
        },
        {
          feature: 'Spectral Centroid Dynamics',
          weight: 0.35,
          description: 'Organic acoustic resonance distribution across vocal formants',
          direction: 'human_bias',
        },
        {
          feature: 'Zero-Crossing Rate Stability',
          weight: 0.18,
          description: 'Uncorrelated ambient micro-fluctuations typical of acoustic room capture',
          direction: 'human_bias',
        },
      ],
      audio_condition: 'Clean (High Signal-to-Noise Ratio)',
      language_match: 'Hindi (hi) — Native acoustic alignment',
      provenance: 'Authentic Human Recording',
      model_name: 'PandaMIND Detector',
      model_version: 'phase9-experimental',
      low_threshold: 0.7408,
      high_threshold: 0.7556,
      flagged_time_ranges: [],
      raw_score: -2.15,
      ece_score: 0.032,
    },
  },
  {
    analysis_id: 'ana_inconclusive_002',
    created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 5 + 4000).toISOString(),
    status: 'completed',
    verdict: 'inconclusive',
    synthetic_probability: 0.745,
    confidence: 0.62,
    error_code: null,
    error_message: null,
    audio: {
      filename: 'whatsapp_voicemail_telecom.opus',
      file_size_bytes: 842100,
      duration_seconds: 12.2,
      sample_rate: 8000,
      channels: 1,
      format: 'OPUS',
      language: 'en',
      degradation: 'whatsapp_opus',
      source: 'telecom_intercept',
    },
    model: {
      name: 'PandaMIND Detector',
      version: 'phase9-experimental',
    },
    evidence: {
      signal_contributions: [
        {
          feature: 'Spectral Flatness Distortion',
          weight: 0.48,
          description: 'Aggressive lossy Opus codec compression flattened spectral detail below 4kHz',
          direction: 'neutral',
        },
        {
          feature: 'Frame Energy Modulation',
          weight: 0.32,
          description: 'Codec dynamic range compression prevents definitive vocoder phase detection',
          direction: 'neutral',
        },
      ],
      audio_condition: 'Degraded (WhatsApp Opus 8kHz Telecom Codec)',
      language_match: 'English (en)',
      provenance: 'Inconclusive acoustic evidence',
      model_name: 'PandaMIND Detector',
      model_version: 'phase9-experimental',
      low_threshold: 0.7408,
      high_threshold: 0.7556,
      flagged_time_ranges: [],
      raw_score: 0.02,
      ece_score: 0.115,
    },
  },
  {
    analysis_id: 'ana_synthetic_003',
    created_at: new Date(Date.now() - 3600000 * 12).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 12 + 3500).toISOString(),
    status: 'completed',
    verdict: 'likely_synthetic',
    synthetic_probability: 0.942,
    confidence: 0.89,
    error_code: null,
    error_message: null,
    audio: {
      filename: 'elevenlabs_v3_cloned_voice.wav',
      file_size_bytes: 3821900,
      duration_seconds: 14.8,
      sample_rate: 24000,
      channels: 1,
      format: 'WAV',
      language: 'en',
      degradation: 'clean',
      source: 'elevenlabs_v3',
    },
    model: {
      name: 'PandaMIND Detector',
      version: 'phase9-experimental',
    },
    evidence: {
      signal_contributions: [
        {
          feature: 'Spectral Flux Inconsistency',
          weight: 0.55,
          description: 'Neural vocoder phase continuity artifacts across high-frequency spectral frames',
          direction: 'synthetic_bias',
        },
        {
          feature: 'Zero-Crossing Regularity',
          weight: 0.28,
          description: 'Unnaturally linear noise floor envelope between phonetic pauses',
          direction: 'synthetic_bias',
        },
        {
          feature: 'Formant Transition Sharpness',
          weight: 0.17,
          description: 'Over-smooth mel-spectrogram synthesis trajectory in consonant transitions',
          direction: 'synthetic_bias',
        },
      ],
      audio_condition: 'Clean (Studio Quality Synthetic Generation)',
      language_match: 'English (en)',
      provenance: 'Synthetic Neural Vocoder (elevenlabs_v3)',
      model_name: 'PandaMIND Detector',
      model_version: 'phase9-experimental',
      low_threshold: 0.7408,
      high_threshold: 0.7556,
      flagged_time_ranges: [
        { start_time: 2.1, end_time: 4.8, label: 'Neural vocoder spectral anomaly', score: 0.96 },
        { start_time: 8.5, end_time: 11.2, label: 'Unnatural formant transition', score: 0.92 },
      ],
      raw_score: 3.42,
      ece_score: 0.041,
    },
  },
  {
    analysis_id: 'ana_failed_004',
    created_at: new Date(Date.now() - 3600000 * 24).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 24 + 1000).toISOString(),
    status: 'failed',
    verdict: null,
    synthetic_probability: null,
    confidence: null,
    error_code: 'AUDIO_DECODE_FAILED',
    error_message: 'Failed to decode the audio stream. The file header is corrupted or truncated.',
    audio: {
      filename: 'corrupted_payload.mp3',
      file_size_bytes: 14200,
      duration_seconds: 0,
      sample_rate: 0,
      channels: 0,
      format: 'MP3',
      language: null,
      degradation: null,
      source: null,
    },
    model: {
      name: 'PandaMIND Detector',
      version: 'phase9-experimental',
    },
    evidence: null,
  },
  {
    analysis_id: 'ana_processing_005',
    created_at: new Date(Date.now() - 5000).toISOString(),
    updated_at: new Date(Date.now() - 2000).toISOString(),
    status: 'processing',
    verdict: null,
    synthetic_probability: null,
    confidence: null,
    error_code: null,
    error_message: null,
    audio: {
      filename: 'tamizh_news_broadcast.mp3',
      file_size_bytes: 2150000,
      duration_seconds: 22.0,
      sample_rate: 44100,
      channels: 2,
      format: 'MP3',
      language: 'ta',
      degradation: 'clean',
      source: 'live_ingest',
    },
    model: {
      name: 'PandaMIND Detector',
      version: 'phase9-experimental',
    },
    evidence: null,
  },
];
